name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install dependencies
      run: |
        npm ci
        composer install

    - name: Set up wp-env
      run: |
        npm run up
        npx wp-env run cli wp core version

    - name: Run JavaScript and CSS linting
      run: npm run lint

    - name: Install Playwright browsers
      run: npx playwright install chromium --with-deps

    - name: Run E2E tests
      run: npm run test:js

    - name: Stop wp-env
      if: always()
      run: npm run down
